/**
 * Changelog Generator API
 * POST /api/changelog
 * 
 * Auto-generates CHANGELOG.md content from heal events and commit messages.
 */
import { NextRequest, NextResponse } from 'next/server';

interface ChangelogEntry {
  date: string;
  type: string;
  message: string;
  model?: string;
  files?: string[];
}

export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => ({}));
  const repoId = body.repoId;
  const limit = body.limit || 50;

  const entries: ChangelogEntry[] = [];

  try {
    const { getDb, schema } = await import('@/lib/db');
    const { desc, eq } = await import('drizzle-orm');
    const db = getDb();

    const query = repoId
      ? db.select().from(schema.healEvents).where(eq(schema.healEvents.repositoryId, repoId)).orderBy(desc(schema.healEvents.createdAt)).limit(limit)
      : db.select().from(schema.healEvents).orderBy(desc(schema.healEvents.createdAt)).limit(limit);

    const events = await query;

    for (const event of events) {
      entries.push({
        date: new Date(event.createdAt).toISOString().split('T')[0],
        type: event.triggerType,
        message: event.commitMessage || 'Documentation heal event',
        model: event.modelUsed || undefined,
        files: (event.modifiedFiles as string[]) || undefined,
      });
    }
  } catch {
    // DB not available — return demo changelog
  }

  // If no DB entries, generate from provided data
  if (!entries.length && body.events) {
    for (const evt of body.events) {
      entries.push({
        date: evt.date || new Date().toISOString().split('T')[0],
        type: evt.type || 'manual',
        message: evt.message || 'Documentation update',
        model: evt.model,
        files: evt.files,
      });
    }
  }

  // Generate markdown changelog
  const changelog = generateChangelog(entries);

  return NextResponse.json({
    success: true,
    changelog,
    entryCount: entries.length,
    entries,
  });
}

function generateChangelog(entries: ChangelogEntry[]): string {
  if (!entries.length) {
    return `# Changelog\n\nNo heal events recorded yet. Connect a repository and trigger a heal to start generating changelog entries.\n`;
  }

  // Group by date
  const grouped: Record<string, ChangelogEntry[]> = {};
  for (const entry of entries) {
    if (!grouped[entry.date]) grouped[entry.date] = [];
    grouped[entry.date].push(entry);
  }

  let md = `# Changelog\n\nAll notable documentation healing events for this project.\n\n_Auto-generated by Ostinato Self-Healing Engine._\n\n`;

  const sortedDates = Object.keys(grouped).sort((a, b) => b.localeCompare(a));

  for (const date of sortedDates) {
    md += `## ${date}\n\n`;

    for (const entry of grouped[date]) {
      const typeEmoji =
        entry.type === 'webhook' ? '🔗' :
        entry.type === 'scheduled' ? '⏰' :
        entry.type === 'manual' ? '✏️' : '📝';

      md += `- ${typeEmoji} **${entry.message}**`;
      if (entry.model) md += ` _(via ${entry.model})_`;
      md += `\n`;
      if (entry.files?.length) {
        for (const f of entry.files) {
          md += `  - \`${f}\`\n`;
        }
      }
    }
    md += '\n';
  }

  return md;
}
