using System;
using System.IO;
using LibGit2Sharp;
using System.Text.Json;

namespace ShadowBrancher
{
    class Program
    {
        static void Main(string[] args)
        {
            if (args.Length < 2)
            {
                Console.WriteLine(JsonSerializer.Serialize(new { error = "Usage: ShadowBrancher <repo_path> <vulnerability_id> [commit_msg]" }));
                return;
            }

            string repoPath = args[0];
            string vulnId = args[1];
            string commitMsg = args.Length > 2 ? args[2] : $"Fix potential vulnerability (ID: {vulnId}) auto-generated by SYNKRON.";
            string branchName = $"synkron/fix-{vulnId}";

            try
            {
                // Ensure we have a valid repository path
                string actualRepoPath = Repository.Discover(repoPath);
                if (string.IsNullOrEmpty(actualRepoPath))
                {
                     Console.WriteLine(JsonSerializer.Serialize(new { success = false, error = "Not a git repository." }));
                     return;
                }

                using (var repo = new Repository(actualRepoPath))
                {
                    // Check if branch already exists
                    var branch = repo.Branches[branchName];
                    if (branch == null)
                    {
                        branch = repo.CreateBranch(branchName);
                        Console.Error.WriteLine($"Created branch: {branchName}");
                    }

                    // Checkout the branch
                    Commands.Checkout(repo, branch);

                    // Stage all changes
                    Commands.Stage(repo, "*");

                    // Set up author & committer identity
                    Signature author = new Signature("SYNKRON Bot", "bot@synkron.ai", DateTimeOffset.Now);
                    Signature committer = author;

                    // Check status to see if there are changes to commit
                    var status = repo.RetrieveStatus();
                    if (status.IsDirty)
                    {
                         // Commit
                         Commit commit = repo.Commit(commitMsg, author, committer);
                         Console.WriteLine(JsonSerializer.Serialize(new { 
                             success = true, 
                             branch = branchName, 
                             commitSha = commit.Sha,
                             message = "Shadow branch created and committed successfully."
                         }));
                    }
                    else
                    {
                         Console.WriteLine(JsonSerializer.Serialize(new { 
                             success = true, 
                             branch = branchName, 
                             message = "Branch switched, but no changes to commit." 
                         }));
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(JsonSerializer.Serialize(new { success = false, error = ex.Message }));
            }
        }
    }
}
