/**
 * PR Description Generator
 * POST /api/webhook/pr-description
 * 
 * Generates a GitHub PR description summarizing what changed,
 * using AI to analyze the code diff and heal events.
 */
import { NextRequest, NextResponse } from 'next/server';
import { generateText } from 'ai';
import { createGroq } from '@ai-sdk/groq';

const groq = createGroq({ apiKey: process.env.GROQ_API_KEY });

export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => ({}));

  const commitMessage = body.commitMessage || 'Code update';
  const modifiedFiles: string[] = body.modifiedFiles || [];
  const branch = body.branch || 'main';
  const repoName = body.repoName || 'unknown/repo';
  const codeDiff = body.codeDiff || '';
  const healSummary = body.healSummary || '';

  const prompt = `You are Ostinato's PR description generator. Generate a concise, professional GitHub Pull Request description.

**Repository:** ${repoName}
**Branch:** ${branch}
**Commit Message:** ${commitMessage}
**Modified Files:** ${modifiedFiles.join(', ') || 'None specified'}
${codeDiff ? `\n**Code Changes:**\n\`\`\`\n${codeDiff.slice(0, 3000)}\n\`\`\`` : ''}
${healSummary ? `\n**Documentation Healing Summary:** ${healSummary}` : ''}

Generate a PR description with:
1. A brief summary (1-2 sentences)
2. A "Changes" section listing what was modified
3. A "Documentation" section noting what docs were auto-healed
4. Testing notes if applicable

Format it as clean Markdown. Be concise and professional.`;

  try {
    const { text } = await generateText({
      model: groq('llama-3.3-70b-versatile'),
      prompt,
      temperature: 0.2,
      maxTokens: 1024,
    });

    return NextResponse.json({
      success: true,
      description: text.trim(),
      metadata: { repoName, branch, commitMessage, modifiedFiles },
    });
  } catch (err: any) {
    // Fallback: generate a simple template without AI
    const fallback = generateFallbackDescription(commitMessage, modifiedFiles, branch, repoName, healSummary);
    return NextResponse.json({
      success: true,
      description: fallback,
      fallback: true,
      metadata: { repoName, branch, commitMessage, modifiedFiles },
    });
  }
}

function generateFallbackDescription(
  commitMessage: string,
  modifiedFiles: string[],
  branch: string,
  repoName: string,
  healSummary: string
): string {
  return `## Summary

${commitMessage}

## Changes

${modifiedFiles.length ? modifiedFiles.map(f => `- \`${f}\``).join('\n') : '- No files specified'}

## Documentation

${healSummary || 'Documentation has been auto-healed by Ostinato to reflect the latest code changes.'}

## Notes

- Branch: \`${branch}\`
- Repository: \`${repoName}\`
- Auto-generated by Ostinato Self-Healing Engine
`;
}
